// Generated by https://quicktype.io

class Tickets {

  List<Ticket> items = new List();

  Tickets();

  Tickets.fromJsonList(List<dynamic> jsonList) {

    if (jsonList == null) return;

    for (var item in jsonList) {
      final ticket = new Ticket.fromJsonMap(item);
      items.add(ticket);
    }
  }
}


class Ticket {
  int numero;
  String escritorio;

  Ticket({
    this.numero,
    this.escritorio,
  });

  factory Ticket.fromJsonMap(Map<String, dynamic> json){
    return new Ticket(
      numero: json['numero'],
      escritorio: json['escritorio']
    );
  }
}

