// Generated by https://quicktype.io

class Ticket {
  String numero;
  String escritorio;

  Ticket({
    this.numero,
    this.escritorio,
  });

  factory Ticket.fromJson(Map<String, dynamic> json){
    return new Ticket(
      numero: json['numero'].toString(),
      escritorio: json['escritorio']
    );
  }
}

class Tickets {
  final List<Ticket> tikets = new List();

  Tickets();

  Tickets.fromJsonList(List<dynamic> parsedJson) {
    for (var item in parsedJson) {
      final pelicula = new Ticket.fromJson(item);
      tikets.add(pelicula);
    }
  }
}
